<?php
$list = array(
"Princeton University",
"Harvard College",
"Yale University",
"Columbia University",
"Stanford University",
"The University of Chicago",
"Duke University",
"Massachusetts Institute of Technology",
"University of Pennsylvania",
"California Institute of Technology",
"Dartmouth College",
"Johns Hopkins University",
"Northwestern University",
"Brown University",
"Washington Univ. in St. Louis",
"Cornell University",
"Vanderbilt University",
"Rice University",
"University of Notre Dame",
"Emory University",
"Georgetown University",
"Univ. of California--Berkeley",
"Carnegie Mellon University",
"Univ. of California--Los Angeles",
"University of Southern California",
"University of Virginia",
"Wake Forest University",
"Tufts University",
"Univ. of Michigan--Ann Arbor",
"Univ. of North Carolina--Chapel Hill",
"Boston College",
"Brandeis University",
"College of William and Mary",
"New York University",
"University of Rochester",
"Georgia Institute of Technology",
"Case Western Reserve University",
"Pennsylvania State University",
"Univ. of California--Davis",
"Univ. of California--San Diego",
"Boston University",
"Lehigh University",
"Rensselaer Polytechnic Institute",
"Univ. of California--Santa Barbara",
"UIUC",
"University of Wisconsin--Madison",
"University of Miami",
"Yeshiva University",
"Northeastern University",
"Univ. of California--Irvine",
"University of Florida",
"George Washington University",
"Ohio State University",
"Tulane University",
"University of Texas--Austin",
"University of Washington",
"Fordham University",
"Pepperdine University",
"University of Connecticut",
"Southern Methodist University",
"University of Georgia",
"Williams College", 
"Amherst College",
"Swarthmore College",
"Bowdoin College",
"Middlebury College",
"Pomona College",
"Carleton College",
"Wellesley College",
"Claremont McKenna College",
"Davidson College",
"Haverford College",
"United States Naval Academy",
"Vassar College",
"Hamilton College",
"Washington and Lee University",
"Harvey Mudd College",
"Grinnell College",
"United States Military Academy",
"Wesleyan University",
"Colgate University",
"Smith College",
"Bates College",
"Colby College",
"Macalester College",
"College of the Holy Cross",
"Oberlin College",
"Scripps College",
"United States Air Force Academy",
"University of Richmond",
"Bryn Mawr College",
"Colorado College",
"Barnard College",
"Bucknell University",
"Kenyon College",
"Pitzer College",
"Lafayette College",
"Trinity College",
"Bard College",
"Mount Holyoke College",
"Sewanee--University of the South",
"Occidental College",
"Soka University of America",
"Union College",
"Whitman College",
"Connecticut College",
"Dickinson College",
"Franklin and Marshall College",
"Skidmore College",
"Centre College",
"Denison University",
"Gettysburg College",
"Furman University",
"St. Olaf College",
"DePauw University",
"Rhodes College",
"St. Lawrence University",
"Wabash College",
"Wheaton College",
"Beloit College",
"Lawrence University");
//echo "No ERR";