<?php
$list = array(
"Princeton University",
"Harvard College",
"Yale University",
"Columbia University",
"Stanford University",
"The University of Chicago",
"Duke University",
"Massachusetts Institute of Technology",
"University of Pennsylvania",
"California Institute of Technology",
"Dartmouth College",
"Johns Hopkins University",
"Northwestern University",
"Brown University",
"Washington Univ. in St. Louis",
"Cornell University",
"Vanderbilt University",
"Rice University",
"University of Notre Dame",
"Emory University",
"Georgetown University",
"Univ. of California--Berkeley",
"Carnegie Mellon University",
"Univ. of California--Los Angeles",
"University of Southern California",
"University of Virginia",
"Wake Forest University",
"Tufts University",
"Univ. of Michigan--Ann Arbor",
"Univ. of North Carolina--Chapel Hill",
"Boston College",
"Brandeis University",
"College of William and Mary",
"New York University",
"University of Rochester",
"Georgia Institute of Technology",
"Case Western Reserve University",
"Pennsylvania State University",
"Univ. of California--Davis",
"Univ. of California--San Diego",
"Boston University",
"Lehigh University",
"Rensselaer Polytechnic Institute",
"Univ. of California--Santa Barbara",
"UIUC",
"University of Wisconsin--Madison",
"University of Miami",
"Yeshiva University",
"Northeastern University",
"Univ. of California--Irvine",
"University of Florida",
"George Washington University",
"Ohio State University",
"Tulane University",
"University of Texas--Austin",
"University of Washington",
"Fordham University",
"Pepperdine University",
"University of Connecticut",
"Southern Methodist University",
"University of Georgia");
//echo "No ERR";